# Generated by Django 3.2.9 on 2021-11-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
